# Generated by Django 4.0.5 on 2022-07-29 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_roomchats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomchats',
            name='room_name',
        ),
    ]
