# Generated by Django 4.0.5 on 2022-07-30 09:56

import accounts.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_roomchats_room_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomchats',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.room'),
        ),
        migrations.AlterField(
            model_name='room',
            name='code',
            field=models.CharField(default=accounts.models.generate_unique_code, max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='roomchats',
            name='user',
            field=models.CharField(default='', max_length=50),
        ),
    ]
