# Generated by Django 4.0.5 on 2022-08-13 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_rename_user_room_host'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomchats',
            name='user',
        ),
    ]
