# Generated by Django 4.0.5 on 2022-08-13 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_roomchats_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomchats',
            name='user',
            field=models.CharField(default='', max_length=50),
        ),
    ]
