# Generated by Django 4.0.5 on 2022-08-21 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_roomchats_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomchats',
            old_name='chat_text',
            new_name='message',
        ),
    ]
