# Generated by Django 4.0.5 on 2022-08-21 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_rename_chat_text_roomchats_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomchats',
            name='message',
            field=models.TextField(null=True),
        ),
    ]
